version: "3"
services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./app:/var/www/app:cached
      - ./services/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx

  php:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "8080:8080"
    working_dir: /var/www/app
    depends_on:
      - memcache
    volumes:
      - ./app:/var/www/app:cached
      - ./services/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./services/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./services/extension/conf.d/docker-php-ext-pcntl.ini:/usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini
      - ./logs/php:/var/log/php
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    command: >
      bash -c "chown -R www-data:www-data /var/www/app/storage /var/www/app/bootstrap/cache &&
               chmod -R 775 /var/www/app/storage /var/www/app/bootstrap/cache &&
               php-fpm"

  memcache:
    image: memcached:latest

volumes:
  mysql-volume:
